data = [
    ("mutlu değilim", 0),
    ("mutsuz değilim", 1),
    ("mutluyum", 1),
    ("kötüyüm", 0),
    ("kötü sayılmam", 1),
    ("mutluyum", 1),
    ("biraz mutsuzum", 0),
    ("keyfim yerinde", 1),
    ("keyfim hiç yok", 0),
    ("harika hissediyorum", 1),
    ("berbat bir gün", 0),
    ("yorgun ama mutluyum", 1),
    ("üzgünüm ama toparlanıyorum", 1),
    ("moralim bozuk", 0),
    ("şu an neşeliyim", 1),
    ("kendimi kötü hissediyorum", 0),
    ("neşeliyim", 1),
    ("biraz moralim düşük", 0),
    ("mutluluk doluyum", 1),
    ("mutsuz ve bitkinim", 0),
    ("iyiyim", 1),
    ("kötü bir ruh halindeyim", 0),
    ("mutlu hissediyorum", 1),
    ("keyifsizim", 0),
    ("mutluyum ve huzurluyum", 1),
    ("moralim kötü", 0),
    ("enerjim yüksek", 1),
    ("biraz üzgünüm", 0),
    ("keyifliyim", 1),
    ("kötü hissediyorum", 0),
    ("neşeliyim", 1),
    ("moralsizim", 0),
    ("mutluyum ama yorgunum", 1),
    ("üzgün ve mutsuzum", 0),
    ("gülümsemek istiyorum", 1),
    ("kendimi kötü hissediyorum", 0),
    ("huzurluyum", 1),
    ("mutsuz bir gün geçiriyorum", 0),
    ("harika bir gün", 1),
    ("moralim düşük", 0),
    ("mutluyum ve pozitifim", 1),
    ("kendimi  kötü hissediyorum", 0),
    ("neşem yerinde", 1),
    ("üzgünüm", 0),
    ("mutlu ve keyifliyim", 1),
    ("moralsiz ve mutsuzum", 0),
    (" iyi hissediyorum", 1),
    ("kötü hissediyorum", 0),
    ("enerjim yüksek ve mutluyum", 1),
    ("moralim bozuk ve üzgünüm", 0),
    ("mutluluk içindeyim", 1),
    ("mutsuzum ve yorgunum", 0),
    ("keyifliyim ve pozitifim", 1),
    ("kendimi kötü ve bitkin hissediyorum", 0),
    ("gülümsemek istiyorum ve mutluyum", 1),
    ("üzgün ve moralsizim", 0),
    ("harika hissediyorum ve keyifliyim", 1),
    ("kötü bir ruh halindeyim", 0),
    ("neşem yerinde ve enerjim yüksek", 1),
    ("moralsiz ve mutsuz hissediyorum", 0),
    ("mutluyum ve huzurluyum", 1),
    ("mutsuz ve yorgunum", 0),
    ("keyifliyim ve gülümsemek istiyorum", 1),
    ("üzgün ve bitkinim", 0),
    (" mutluyum", 1),
    ("kendimi kötü hissediyorum", 0),
    ("neşeliyim ve enerjim yüksek", 1),
    ("moralsiz ve mutsuzum", 0),
    ("mutlu hissediyorum", 1),
    ("üzgün ve keyifsizim", 0),
    ("harika hissediyorum", 1),
    ("moralim bozuk", 0),
    ("mutluyum ve pozitifim", 1),
    ("mutsuz ve yorgunum", 0),
    ("neşeliyim", 1),
    ("kötü hissediyorum", 0),
    ("mutluyum ve huzurluyum", 1),
    ("üzgünüm", 0),
    ("keyfim yerinde", 1),
    ("moralsizim", 0),
    ("keyifliyim", 1),
    ("mutsuzum", 0),
    ("gülümsemek istiyorum", 1),
    ("kendimi kötü hissediyorum", 0),
    ("mutluluk doluyum", 1),
    ("moralsiz ve üzgünüm", 0),
    ("enerjim yüksek", 1),
    ("kötü bir gün geçiriyorum", 0),
    ("mutluyum ve neşeliyim", 1),
    ("üzgün ve moralsizim", 0),
    ("harika bir ruh halindeyim", 1),
    ("mutsuz ve bitkinim", 0),
    ("mutluyum", 1),
    ("kendimi kötü hissediyorum", 0),
    ("neşem yerinde", 1),
    ("moralsiz ve mutsuzum", 0),
    ("keyifliyim", 1),
    ("üzgün ve yorgunum", 0),
    ("gülümsemek istiyorum", 1),
    ("kötü hissediyorum", 0),
    ("mutluyum ve huzurluyum", 1),
    ("moralim bozuk", 0),
    ("enerjim yüksek ve mutluyum", 1),
    ("mutsuz ve moralsizim", 0),
    ("harika hissediyorum", 1),
    ("üzgünüm", 0),
    ("mutluyum ve pozitifim", 1),
    ("moralsiz ve mutsuzum", 0),
    ("neşeliyim", 1),
    ("kötü bir ruh halindeyim", 0),
    ("mutluluk içindeyim", 1),
    ("mutsuz ve yorgunum", 0),
    (" keyifliyim", 1),
    ("kendimi kötü hissediyorum", 0),
        # Pozitif cümleler (1)
    ("mutluyum", 1),
    ("harika bir gün", 1),
    ("güneşli ve güzel bir sabah", 1),
    ("başarıyla tamamladım", 1),
    ("sevinçliyim", 1),
    ("harika hissediyorum", 1),
    ("moralim  iyi", 1),
    ("güzel bir sürpriz aldım", 1),
    ("şanslıyım", 1),
    ("heyecanlıyım", 1),
    ("harika bir haber aldım", 1),
    ("kendimi harika hissediyorum", 1),
    ("neşeliyim", 1),
    ("pozitif enerji doluyum", 1),
    ("keyfim yerinde", 1),
    ("heyecanlıyım", 1),
    ("mutlu bir gün geçiriyorum", 1),
    ("başarılı oldum", 1),
    ("güzel bir tatil planladım", 1),
    ("huzurluyum", 1),
    ("gururluyum", 1),
    ("heyecan verici bir fırsat", 1),
    ("gülümsemek istiyorum", 1),
    ("iyi hissediyorum", 1),
    ("güzel bir gün", 1),
    ("enerjim yüksek", 1),
    ("harika bir başlangıç", 1),
    ("umutluyum", 1),
    ("başarı beni mutlu etti", 1),
    ("keyifliyim", 1),
    ("güzel bir yemek yedim", 1),
    ("pozitif bir gün", 1),
    ("kendimi iyi hissediyorum", 1),
    ("tatmin oldum", 1),
    ("harika bir etkinlik", 1),
    ("eğleniyorum", 1),
    ("güzel bir sürpriz", 1),
    ("motiveyim", 1),
    ("mutluluk doluyum", 1),
    ("harika bir haber", 1),
    ("keyfim  yerinde", 1),
    ("başarılı hissediyorum", 1),
    ("güzel bir anı", 1),
    ("pozitif bir enerji", 1),
    ("sevindim", 1),
    ("harika bir başlangıç yaptım", 1),
    ("mutluyum", 1),
    ("neşeliyim", 1),
    ("iyi hisler içerisindeyim", 1),
    ("huzurluyum", 1),
    ("başarıdan dolayı mutluyum", 1),
    ("gülmek istiyorum", 1),
    ("keyifli bir gün", 1),
    ("her şey yolunda", 1),
    ("sevindim", 1),
    ("harika bir deneyim", 1),
    ("mutluluk verici bir an", 1),
    ("umutluyum", 1),
    ("pozitif düşüncelerle doluyum", 1),
    ("başarıya ulaştım", 1),
    ("memnunum", 1),
    ("harika bir tatil geçirdim", 1),
    ("mutlu oldum", 1),
    ("güzel bir sürprizle karşılaştım", 1),
    ("heyecanlı ve mutluyum", 1),
    ("pozitif bir başlangıç", 1),
    ("keyifliyim", 1),
    ("harika bir haberle sevindim", 1),
    ("şanslı hissettim", 1),
    ("güzel bir gün geçirdim", 1),
    ("motiveyim", 1),
    ("başarı beni gururlandırdı", 1),
    ("neşeliyim", 1),
    ("keyifli vakit geçirdim", 1),
    ("huzurluyum", 1),
    ("pozitif bir enerji hissediyorum", 1),
    ("mutluyum bu an için", 1),
    ("güzel bir gün yaşadım", 1),
    ("sevindim bu yüzden", 1),
    ("harika bir his", 1),
    ("keyifli bir deneyim", 1),
    ("heyecanlı ve mutluyum", 1),
    ("pozitif bir ruh halindeyim", 1),
    ("tatmin oldum", 1),
    ("başarıdan dolayı mutluyum", 1),
    ("gururluyum", 1),
    ("güzel bir haber aldım", 1),
    ("neşeliyim bu an", 1),
    ("mutluyum ve huzurluyum", 1),
    ("pozitif bir gün geçirdim", 1),
    ("keyifli bir gün", 1),
    ("harika bir başlangıç yaptım", 1),
    ("motive oldum", 1),
    ("mutlu hissettim", 1),
    ("güzel bir gün yaşamak harika", 1),
    ("sevindim bu an için", 1),
    ("keyif aldım", 1),
    ("pozitif duygular içerisindeyim", 1),
    ("heyecanlı ve keyifliyim", 1),
    ("mutluyum ve başarılıyım", 1),
    ("harika bir gün geçirdim", 1),
    ("sevindim", 1),
    ("pozitif bir ruh halindeyim", 1),
    ("keyifli ve mutluyum", 1),
    ("huzurluyum ve mutlu", 1),
    ("gururluyum bu an için", 1),
    ("tatmin oldum bu yüzden", 1),
    ("güzel bir an yaşadım", 1),
    ("mutluyum ve heyecanlıyım", 1),
    ("pozitif bir başlangıç yaptım", 1),
    ("neşeliyim ve keyifliyim", 1),
    ("şanslı ve mutluyum", 1),
    ("keyif aldım", 1),
    ("motivasyonluyum", 1),
    ("mutluyum ve pozitifim", 1),
    ("harika bir gün yaşadım", 1),
    ("heyecanlı ve neşeliyim", 1),
    ("keyifliyim ve huzurluyum", 1),
    ("mutlu ve motiveyim", 1),
    ("pozitif bir deneyim yaşadım", 1),
    ("gururluyum ve mutluyum", 1),
    ("tatmin oldum", 1),
    ("heyecanlı ve başarılıyım", 1),
    ("neşeliyim ve pozitifim", 1),
    ("keyifli bir an yaşadım", 1),
    ("mutluyum ve heyecanlıyım", 1),
    ("harika bir his yaşadım", 1),
    ("motivasyonluyum ve mutluyum", 1),
    ("keyif aldım bu an için", 1),
    ("mutlu ve pozitif bir ruh halindeyim", 1),
    ("pozitif bir gün yaşadım", 1),
    ("huzurluyum ve keyifliyim", 1),
    ("heyecanlı ve tatmin oldum", 1),
    ("gururluyum ve keyifliyim", 1),
    ("mutluyum ve şanslıyım", 1),
    ("harika bir deneyim yaşadım", 1),
    ("keyifli ve heyecanlıyım", 1),
    ("pozitif bir enerji doluyum", 1),
    ("mutlu ve neşeliyim", 1),
    ("heyecanlı ve motiveyim", 1),
    ("keyif aldım", 1),
    ("huzurluyum ve mutlu", 1),
    ("mutluyum ve başarılıyım", 1),
    ("harika bir başlangıç yaşadım", 1),
    ("pozitif bir ruh halindeyim", 1),
    ("motivasyonluyum ve keyifliyim", 1),
    ("neşeliyim ve mutluyum", 1),
    ("heyecanlı ve şanslıyım", 1),
    ("keyifli ve huzurluyum", 1),
    ("mutluyum ve pozitif enerji doluyum", 1),
    ("harika bir gün yaşamak  güzel", 1),
    ("motivasyonluyum", 1),
    ("heyecanlı ve tatmin oldum", 1),
    ("keyif aldım ve mutluyum", 1),
    ("pozitif bir gün geçirdim", 1),
    ("gururluyum ve motiveyim", 1),
    ("mutluyum ve keyifliyim", 1),
    ("harika bir haberle sevindim", 1),
    ("heyecanlı ve neşeliyim", 1),
    ("huzurluyum ve başarılıyım", 1),
    ("pozitif bir enerji hissettim", 1),
    ("mutlu ve tatmin oldum", 1),
    ("keyifli ve heyecanlıyım", 1),
    ("mutluyum ve gururluyum", 1),
    ("harika bir gün geçirdim", 1),
    ("pozitif bir ruh halindeyim", 1),
    ("heyecanlı ve pozitifim", 1),
    ("motivasyonluyum ve mutluyum", 1),
    ("keyif aldım ve huzurluyum", 1),
    ("mutluyum ve şanslıyım", 1),
    ("harika bir deneyim yaşadım", 1),
    ("heyecanlı ve keyifliyim", 1),
    ("pozitif bir enerji doluyum", 1),
    ("mutlu ve motiveyim", 1),
    ("keyifli ve neşeliyim", 1),
    ("mutluyum ve tatmin oldum", 1),
    ("harika bir gün yaşadım", 1),
    ("pozitif bir ruh halindeyim şimdi", 1),
    ("heyecanlı ve gururluyum", 1),
    ("keyif aldım ve pozitifim", 1),
    ("mutluyum ve heyecanlıyım", 1),
    ("harika bir haber aldım", 1),
    ("pozitif bir enerji hissettim", 1),
    ("motivasyonluyum ve heyecanlıyım", 1),
    ("neşeliyim ve keyifliyim", 1),
    ("mutluyum ve gururluyum", 1),
    ("harika bir gün yaşamak  keyifli", 1),
    ("pozitif bir ruh halindeyim şimdi", 1),
    ("heyecanlı ve motiveyim", 1),
    ("keyif aldım ve mutluyum", 1),
    ("mutluyum ve pozitif enerji doluyum", 1),
    # Negatif cümleler (0)
    ("üzgünüm", 0),
    ("berbat bir gün", 0),
    ("hiç mutlu değilim", 0),
    ("moralsizim", 0),
    ("kötü bir haber aldım", 0),
    ("sıkıldım", 0),
    ("kendimi kötü hissediyorum", 0),
    ("mutsuzum", 0),
    ("yorgunum", 0),
    ("olumsuz bir gün", 0),
    ("üzücü bir haber", 0),
    ("kötü bir başlangıç", 0),
    ("huzursuzum", 0),
    ("hayal kırıklığına uğradım", 0),
    ("stresliyim", 0),
    ("endişeliyim", 0),
    ("moralsiz bir gün", 0),
    ("hayal kırıklığı", 0),
    ("kötü hissediyorum", 0),
    ("keyfim yok", 0),
    ("kırgınım", 0),
    ("rahatsız hissediyorum", 0),
    ("çıkmazdayım", 0),
    ("karamsarım", 0),
    ("hayal kırıklığı içindeyim", 0),
    ("sinirliyim", 0),
    ("kötü bir olay", 0),
    ("üzücü bir durum", 0),
    ("hiç keyfim yok", 0),
    ("mutsuzum", 0),
    ("umutsuz hissediyorum", 0),
    ("hayal kırıklığına uğradım", 0),
    ("moralsiz ve mutsuzum", 0),
    ("endişeliyim", 0),
    ("kötü bir gün geçirdim", 0),
    ("yorgun ve üzgünüm", 0),
    ("sinirliyim", 0),
    ("üzücü bir haber aldım", 0),
    ("mutsuzum ve keyifsizim", 0),
    ("moralsiz hissediyorum", 0),
    ("stresliyim", 0),
    ("kötü bir başlangıç yaptım", 0),
    ("üzgün ve kırgınım", 0),
    ("hiç mutlu değilim", 0),
    ("karamsarım", 0),
    ("rahatsız hissediyorum", 0),
    ("üzücü bir deneyim yaşadım", 0),
    ("mutsuzum ve yorgunum", 0),
    ("moralsiz ve endişeliyim", 0),
    ("hayal kırıklığı içindeyim", 0),
    ("sinirliyim ve üzgünüm", 0),
    ("mutsuz ve moralsizim", 0),
    ("kötü bir haber aldım", 0),
    ("yorgun ve karamsarım", 0),
    ("üzücü bir olay yaşadım", 0),
    ("mutsuz ve stresliyim", 0),
    ("hiç keyfim yok", 0),
    ("endişeli ve moralsizim", 0),
    ("sinirliyim ve yorgunum", 0),
    ("moralsiz ve mutsuz bir gün", 0),
    ("kötü hissediyorum", 0),
    ("üzgün ve karamsarım", 0),
    ("kötü bir deneyim yaşadım", 0),
    ("hayal kırıklığına uğradım", 0),
    ("moralsiz ve stresliyim", 0),
    ("mutsuz ve rahatsız hissediyorum", 0),
    ("hiç mutlu değilim bu an", 0),
    ("sinirliyim ve moralsizim", 0),
    ("üzgün ve endişeliyim", 0),
    ("kötü bir gün geçirdim", 0),
    ("yorgun ve mutsuzum", 0),
    ("moralsiz ve rahatsız hissediyorum", 0),
    ("hayal kırıklığı yaşadım", 0),
    ("sinirliyim ve stresliyim", 0),
    ("mutsuz ve karamsarım", 0),
    ("üzücü bir haber aldım", 0),
    ("hiç keyfim yok bu an", 0),
    ("moralsiz ve endişeliyim", 0),
    ("yorgun ve sinirliyim", 0),
    ("kötü bir başlangıç yaptım", 0),
    ("mutsuz ve rahatsızım", 0),
    ("moralsiz ve üzgünüm", 0),
    ("stresliyim ve mutsuzum", 0),
    ("sinirliyim ve karamsarım", 0),
    ("üzücü bir deneyim yaşadım", 0),
    ("mutsuz ve endişeliyim", 0),
    ("hiç mutlu değilim ve moralsizim", 0),
    ("yorgun ve rahatsızım", 0),
    ("moralsiz ve hayal kırıklığı içindeyim", 0),
    ("üzgün ve stresliyim", 0),
    ("kötü bir haberle karşılaştım", 0),
    ("mutsuz ve sinirliyim", 0),
    ("moralsiz ve yorgunum", 0),
    ("hayal kırıklığına uğradım bu an", 0),
    ("mutsuz ve rahatsız hissediyorum", 0),
    ("hiç keyfim yok ve karamsarım", 0),
    ("sinirliyim ve üzgünüm", 0),
    ("kötü bir gün geçirdim bu an", 0),
    ("moralsiz ve endişeliyim", 0),
    ("mutsuz ve stresliyim", 0),
    ("üzücü bir haber aldım bu an", 0),
    ("yorgun ve moralsizim", 0),
    ("moralsiz ve mutsuz bir gün", 0),
    ("sinirliyim ve yorgunum", 0),
    ("üzgün ve karamsarım", 0),
    ("kötü bir deneyim yaşadım", 0),
    ("mutsuz ve rahatsızım bu an", 0),
    ("moralsiz ve stresliyim", 0),
    ("hayal kırıklığı yaşadım", 0),
        ("hiç mutlu değilim bu an", 0),
    ("mutsuz ve moralsizim", 0),
    ("yorgun ve stresliyim", 0),
    ("moralsiz ve karamsarım", 0),
    ("sinirliyim ve rahatsızım", 0),
    ("üzücü bir olay yaşadım", 0),
    ("mutsuz ve endişeliyim", 0),
    ("kötü bir haber aldım bu an", 0),
    ("moralsiz ve mutsuz bir gün", 0),
    ("hayal kırıklığına uğradım bu an", 0),
    ("yorgun ve moralsizim", 0),
    ("hiç keyfim yok ve stresliyim", 0),
    ("sinirliyim ve mutsuzum", 0),
    ("üzücü bir haberle karşılaştım", 0),
    ("kötü bir gün geçirdim bu an", 0),
    ("moralsiz ve yorgunum", 0),
    ("mutsuz ve rahatsız hissediyorum", 0),
    ("sinirliyim ve endişeliyim", 0),
    ("kötü bir başlangıç yaptım bu gün", 0),
    ("moralsiz ve hayal kırıklığı içindeyim", 0),
    ("üzgün ve karamsarım", 0),
    ("mutsuz ve stresliyim", 0),
    ("hiç keyfim yok ve mutsuzum", 0),
    ("sinirliyim ve moralsizim", 0),
    ("moralsiz ve yorgun hissediyorum", 0),
    ("hayal kırıklığına uğradım", 0),
    ("mutsuz ve rahatsızım", 0),
    ("üzücü bir deneyim yaşadım bu an", 0),
    ("sinirliyim ve karamsarım", 0),
    ("moralsiz ve stresliyim", 0),
    ("mutsuz ve endişeliyim", 0),
    ("hiç mutlu değilim ve keyfim yok", 0),
    ("yorgun ve rahatsız hissediyorum", 0),
    ("moralsiz ve hayal kırıklığı içindeyim", 0),
    ("üzgün ve stresliyim", 0),
    ("kötü bir haberle karşılaştım bu an", 0),
    ("mutsuz ve sinirliyim", 0),
    ("moralsiz ve yorgunum", 0),
    ("hayal kırıklığı yaşadım bu an", 0),
    ("hiç keyfim yok ve karamsarım", 0),
    ("mutsuz ve rahatsız hissediyorum", 0),
    ("üzücü bir haber aldım", 0),
    ("sinirliyim ve moralsizim", 0),
    ("moralsiz ve mutsuz bir gün", 0),
    ("yorgun ve endişeliyim", 0),
    ("hiç mutlu değilim ve rahatsız hissediyorum", 0),
    ("sinirliyim ve stresliyim", 0),
    ("kötü bir deneyim yaşadım", 0),
    ("moralsiz ve hayal kırıklığı içindeyim bu gün", 0),
    ("mutsuz ve karamsarım", 0),
    ("hiç keyfim yok ve mutsuzum", 0),
    ("sinirliyim ve rahatsızım", 0),
    ("üzücü bir olay yaşadım bu gün", 0),
    ("mutsuz ve moralsizim", 0),
    ("moralsiz ve yorgunum bu gün", 0),
    ("hayal kırıklığına uğradım bu gün", 0),
    ("mutsuz ve endişeliyim", 0),
    ("hiç mutlu değilim ve karamsarım", 0),
    ("yorgun ve stresliyim", 0),
    ("moralsiz ve mutsuzum", 0),
    ("sinirliyim ve rahatsız hissediyorum", 0),
    ("üzücü bir haber aldım bu gün", 0),
    ("kötü bir başlangıç yaptım", 0),
    ("mutsuz ve karamsarım", 0),
    ("moralsiz ve stresliyim bu gün", 0),
    ("hayal kırıklığı yaşadım", 0),
    ("hiç keyfim yok ve moralsizim", 0),
    ("sinirliyim ve endişeliyim", 0),
    ("moralsiz ve yorgun hissediyorum", 0),
    ("mutsuz ve rahatsızım bu gün", 0),
    ("üzücü bir deneyim yaşadım", 0),
    ("sinirliyim ve karamsarım bu gün", 0),
    ("moralsiz ve stresliyim", 0),
    ("mutsuz ve endişeliyim", 0),
    ("hiç mutlu değilim ve mutsuzum", 0),
    ("yorgun ve rahatsız hissediyorum", 0),
    ("moralsiz ve hayal kırıklığı içindeyim", 0),
    ("üzgün ve stresliyim", 0),
    ("kötü bir haberle karşılaştım", 0),
    ("mutsuz ve sinirliyim", 0),
    ("moralsiz ve yorgunum", 0),
    ("hayal kırıklığı yaşadım", 0),
    ("hiç keyfim yok ve karamsarım", 0),
        ("mutluyum ve heyecanlıyım", 1),
    ("güzel bir gün geçiriyorum", 1),
    ("sevindim", 1),
    ("harika bir haber aldım", 1),
    ("keyfim yerinde ve neşeliyim", 1),
    ("pozitif hissediyorum", 1),
    ("enerjik ve mutluyum", 1),
    ("motiveyim", 1),
    ("güzel bir sürprizle karşılaştım", 1),
    ("tatmin oldum", 1),
    ("heyecanlıyım ve mutlu", 1),
    ("harika bir anı yaşadım", 1),
    ("pozitif bir enerji hissediyorum", 1),
    ("neşeliyim ve keyifliyim", 1),
    ("gururluyum ve mutluyum", 1),
    ("başarıdan dolayı  mutluyum", 1),
    ("heyecanlı ve tatmin oldum", 1),
    ("harika bir başlangıç yaptım", 1),
    ("keyifli bir gün geçirdim", 1),
    ("huzurluyum ve mutlu", 1),
    ("pozitif bir ruh halindeyim", 1),
    ("mutlu ve motiveyim", 1),
    ("keyif aldım bu an için", 1),
    ("harika bir gün yaşamak  güzel", 1),
    ("heyecanlı ve pozitifim", 1),
    ("neşeliyim ve huzurluyum", 1),
    ("gururluyum ve keyifliyim", 1),
    ("mutluyum ve enerjikim", 1),
    ("pozitif bir gün geçirdim", 1),
    ("tatmin oldum ve mutlu", 1),
    ("harika bir haberle sevindim", 1),
    ("heyecanlı ve gururluyum", 1),
    ("keyifli ve neşeliyim", 1),
    ("mutlu ve pozitif enerji doluyum", 1),
    ("harika bir deneyim yaşadım", 1),
    ("motive ve heyecanlıyım", 1),
    ("huzurluyum ve keyifliyim", 1),
    ("pozitif bir ruh halindeyim", 1),
    ("mutluyum ve gururluyum", 1),
    ("keyif aldım ve heyecanlıyım", 1),
    ("harika bir gün geçirdim", 1),
    ("heyecanlı ve tatmin oldum", 1),
    ("mutlu ve keyifliyim", 1),
    ("pozitif bir enerji doluyum", 1),
    ("neşeliyim ve motiveyim", 1),
    ("gururluyum ve huzurluyum", 1),
    ("mutluyum ve enerjim yüksek", 1),
    ("harika bir başlangıç yaşadım", 1),
    ("heyecanlı ve pozitifim", 1),
    ("keyifli ve tatmin oldum", 1),
    ("pozitif bir gün geçirdim", 1),
    ("mutlu ve heyecanlıyım", 1),
    ("harika bir an yaşamak  güzel", 1),
    ("neşeliyim ve gururluyum", 1),
    ("keyif aldım ve mutlu", 1),
    ("pozitif bir enerji hissediyorum", 1),
    ("huzurluyum ve motiveyim", 1),
    ("mutluyum ve tatmin oldum", 1),
    ("harika bir haberle sevindim", 1),
    ("heyecanlı ve enerjikim", 1),
    ("gururluyum ve keyifliyim", 1),
    ("neşeliyim ve pozitifim", 1),
    ("pozitif bir ruh halindeyim bu an", 1),
    ("mutlu ve keyifli bir gün", 1),
    ("harika bir gün yaşamak  keyifli", 1),
    ("motive ve neşeliyim", 1),
    ("huzurluyum ve enerjim yüksek", 1),
    ("pozitif bir deneyim yaşadım", 1),
    ("heyecanlı ve gururluyum", 1),
    ("keyifli ve mutlu", 1),
    ("mutluyum ve pozitif enerji doluyum", 1),
    ("harika bir başlangıç yaptım", 1),
    ("neşeliyim ve heyecanlıyım", 1),
    ("pozitif bir gün geçiriyorum", 1),
    ("gururluyum ve motiveyim", 1),
    ("mutlu ve tatmin oldum", 1),
    ("harika bir deneyim yaşadım", 1),
    ("heyecanlı ve keyifliyim", 1),
    ("huzurluyum ve neşeliyim", 1),
    ("pozitif bir enerji hissediyorum bu an", 1),
    ("mutluyum ve gururluyum bu an", 1),
    ("keyif aldım ve heyecanlıyım", 1),
    ("harika bir gün geçirdim bu an", 1),
    ("neşeliyim ve pozitifim", 1),
    ("motivasyonluyum ve mutlu", 1),
    ("pozitif bir ruh halindeyim şimdi", 1),
    ("mutluyum ve enerjikim", 1),
    ("keyifli ve heyecanlıyım", 1),
    ("harika bir haber aldım bu an", 1),
    ("heyecanlı ve gururluyum bu an", 1),
    ("huzurluyum ve pozitifim", 1),
    ("pozitif bir gün yaşamak  güzel", 1),
    ("mutluyum ve keyifliyim bu an", 1),
    ("harika bir deneyim yaşamak  güzel", 1),
    ("heyecanlı ve tatmin oldum bu an", 1),
    ("neşeliyim ve gururluyum bu an", 1),
    ("pozitif bir enerji doluyum bu an", 1),
    ("mutluyum ve motiveyim bu an", 1),
    ("keyifli ve enerjikim", 1),
    ("harika bir gün yaşadım bu an", 1),
    ("heyecanlı ve pozitifim bu an", 1),
    ("pozitif bir ruh halindeyim bu gün", 1),
    ("mutlu ve gururluyum bu gün", 1),
    ("neşeliyim ve heyecanlıyım bu gün", 1),
    ("harika bir başlangıç yaptım bu gün", 1),
    ("mutluyum ve keyif aldım bu gün", 1),
    ("heyecanlı ve tatmin oldum bu gün", 1),
    ("pozitif bir gün geçiriyorum bu gün", 1),
    ("gururluyum ve motivasyonluyum", 1),
    ("mutluyum ve pozitifim bu gün", 1),
    ("harika bir deneyim yaşadım bu gün", 1),
    ("heyecanlı ve keyifliyim bu gün", 1),
    ("huzurluyum ve neşeliyim bu gün", 1),
    ("pozitif bir enerji hissediyorum bu gün", 1),
    ("mutluyum ve gururluyum bu gün", 1),
    ("keyif aldım ve heyecanlıyım bu gün", 1),
    ("harika bir gün geçirdim bu gün", 1),
    ("neşeliyim ve pozitifim bu gün", 1),
    ("motivasyonluyum ve mutluyum bu gün", 1),
    ("pozitif bir ruh halindeyim bu gün", 1),
    ("mutluyum ve enerjikim bu gün", 1),
    ("keyifli ve heyecanlıyım bu gün", 1),
    ("harika bir haber aldım bu gün", 1),
    ("heyecanlı ve gururluyum bu gün", 1),
    ("huzurluyum ve pozitifim bu gün", 1),
    ("pozitif bir gün yaşamak  keyifli", 1),
    ("mutluyum ve keyifliyim bu gün", 1),
    ("harika bir deneyim yaşamak  keyifli", 1),
    ("heyecanlı ve tatmin oldum bu gün", 1),
    ("neşeliyim ve gururluyum bu gün", 1),
    ("pozitif bir enerji doluyum bu gün", 1),
    ("mutluyum ve motiveyim bu gün", 1),
    ("keyifli ve enerjikim bu gün", 1),
    ("harika bir gün yaşadım bu gün", 1),
    ("heyecanlı ve pozitifim bu gün", 1),
    ("pozitif bir ruh halindeyim bu gün", 1),
    ("mutlu ve gururluyum bu gün", 1),
    ("neşeliyim ve heyecanlıyım bu gün", 1),
    ("harika bir başlangıç yaptım bu gün", 1),
    ("mutluyum ve keyif aldım bu gün", 1),
    ("heyecanlı ve tatmin oldum bu gün", 1),
    ("pozitif bir gün geçiriyorum bu gün", 1),
    ("gururluyum ve motivasyonluyum", 1),
    ("mutluyum ve pozitifim bu gün", 1),
    ("üzgünüm ve moralsizim", 0),
    ("berbat bir gün geçirdim", 0),
    ("hiç mutlu değilim", 0),
    ("moralsiz ve yorgunum", 0),
    ("kötü bir haber aldım", 0),
    ("sıkıldım ve mutsuzum", 0),
    ("kendimi kötü hissediyorum", 0),
    ("mutsuzum ve keyifsizim", 0),
    ("yorgunum ve moralsizim", 0),
    ("olumsuz bir gün geçiriyorum", 0),
    ("üzücü bir haber aldım", 0),
    ("kötü bir başlangıç yaptım", 0),
    ("huzursuzum ve karamsarım", 0),
    ("hayal kırıklığına uğradım", 0),
    ("stresliyim ve üzgünüm", 0),
    ("endişeliyim ve moralsizim", 0),
    ("moralsiz bir gün geçiriyorum", 0),
    ("hayal kırıklığı içindeyim", 0),
    ("kötü hissediyorum", 0),
    ("keyfim yok ve mutsuzum", 0),
    ("kırgınım ve huzursuzum", 0),
    ("rahatsız hissediyorum", 0),
    ("çıkmazdayım ve endişeliyim", 0),
    ("karamsarım", 0),
    ("hayal kırıklığı içindeyim bu gün", 0),
    ("sinirliyim ve moralsizim", 0),
    ("kötü bir olay yaşadım", 0),
    ("üzücü bir durum yaşadım", 0),
    ("hiç keyfim yok ve karamsarım", 0),
    ("mutsuzum ve üzgünüm", 0),
    ("umutsuz hissediyorum", 0),
    ("hayal kırıklığına uğradım bu gün", 0),
    ("moralsiz ve mutsuz hissediyorum", 0),
    ("endişeliyim ve karamsarım", 0),
    ("kötü bir gün geçirdim", 0),
    ("yorgun ve üzgünüm", 0),
    ("sinirliyim  ve moralsizim", 0),
    ("üzücü bir haber aldım bu gün", 0),
    ("mutsuzum ve keyifsizim", 0),
    ("moralsiz hissediyorum", 0),
    ("stresliyim  ve mutsuzum", 0),
    ("kötü bir başlangıç yaptım bu gün", 0),
    ("üzgün ve kırgınım", 0),
    ("hiç mutlu değilim  ve karamsarım", 0),
    ("karamsarım ve moralsizim", 0),
    ("rahatsız hissediyorum", 0),
    ("üzücü bir deneyim yaşadım", 0),
    ("mutsuz ve yorgunum", 0),
    ("moralsiz ve endişeliyim", 0),
    ("hayal kırıklığı içindeyim", 0),
    ("sinirliyim ve üzgünüm", 0),
    ("mutsuz ve moralsizim", 0),
    ("kötü bir haber aldım bu gün", 0),
    ("yorgun ve karamsarım", 0),
    ("üzücü bir olay yaşadım bu gün", 0),
    ("mutsuz ve stresliyim", 0),
    ("hiç keyfim yok ve moralsizim", 0),
    ("endişeli ve karamsarım", 0),
    ("sinirliyim ve yorgunum", 0),
    ("moralsiz ve mutsuz bir gün", 0),
    ("kötü hissediyorum  ve üzgünüm", 0),
    ("üzgün ve karamsarım", 0),
    ("kötü bir deneyim yaşadım bu gün", 0),
    ("mutsuz ve rahatsızım", 0),
    ("moralsiz ve stresliyim", 0),
    ("hayal kırıklığı yaşadım bu gün", 0),
    ("hiç keyfim yok ve moralsizim", 0),
    ("sinirliyim ve endişeliyim", 0),
    ("moralsiz ve yorgun hissediyorum", 0),
    ("mutsuz ve rahatsızım", 0),
    ("üzücü bir deneyim yaşadım bu gün", 0),
    ("sinirliyim ve karamsarım", 0),
    ("moralsiz ve stresliyim", 0),
    ("mutsuz ve endişeliyim", 0),
    ("hiç mutlu değilim ve mutsuzum", 0),
    ("yorgun ve rahatsız hissediyorum", 0),
    ("moralsiz ve hayal kırıklığı içindeyim", 0),
    ("üzgün ve stresliyim", 0),
    ("kötü bir haberle karşılaştım", 0),
    ("mutsuz ve sinirliyim", 0),
    ("moralsiz ve yorgunum", 0),
    ("hayal kırıklığı yaşadım", 0),
    ("hiç keyfim yok ve karamsarım", 0),
    ("mutsuz ve rahatsız hissediyorum", 0),
    ("üzücü bir haber aldım", 0),
    ("sinirliyim ve moralsizim", 0),
    ("moralsiz ve mutsuz bir gün", 0),
    ("yorgun ve endişeliyim", 0),
    
    ("hiç mutlu değilim ve rahatsız hissediyorum", 0),


    ("sinirliyim ve stresliyim", 0),
    ("kötü bir deneyim yaşadım", 0),
    ("moralsiz ve hayal kırıklığı içindeyim bu gün", 0),
    ("mutsuz ve karamsarım", 0),
    ("hiç keyfim yok ve mutsuzum", 0),
    ("sinirliyim ve rahatsızım", 0),
    ("üzücü bir olay yaşadım bu gün", 0),
    ("mutsuz ve moralsizim", 0),
    ("moralsiz ve yorgunum bu gün", 0),
    ("hayal kırıklığına uğradım bu gün", 0),
    ("mutsuz ve endişeliyim", 0),
    ("hiç mutlu değilim ve karamsarım", 0),
    ("yorgun ve stresliyim", 0),
    ("moralsiz ve mutsuzum", 0),
    ("sinirliyim ve rahatsız hissediyorum", 0),
    ("üzücü bir haber aldım bu gün", 0),
    ("kötü bir başlangıç yaptım", 0),
    ("mutsuz ve karamsarım", 0),
    ("moralsiz ve stresliyim bu gün", 0),
    ("hayal kırıklığı yaşadım", 0),
    # Çelişkili durumlar - "ama" ile olumlu sonuçlanan cümleler
    ("biraz yorgunum ama keyfim yerinde", 1),
    ("yorgunum ama mutluyum", 1),
    ("biraz üzgünüm ama keyfim yerinde", 1),
    ("moralsizim ama toparlanıyorum", 1),
    ("yorgunum ama neşeliyim", 1),
    ("biraz mutsuzum ama keyfim yerinde", 1),
    ("yorgunum ama huzurluyum", 1),
    ("biraz kötüyüm ama keyfim yerinde", 1),
]
