data = [
    ("mutlu değilim", 0),
    ("mutsuz değilim", 1),
    ("mutluyum", 1),
    ("kötüyüm", 0),
    ("kötü sayılmam", 1),
    ("çok mutluyum", 1),
    ("biraz mutsuzum", 0),
    ("keyfim yerinde", 1),
    ("keyfim hiç yok", 0),
    ("harika hissediyorum", 1),
    ("berbat bir gün", 0),
    ("yorgun ama mutluyum", 1),
    ("üzgünüm ama toparlanıyorum", 1),
    ("moralim bozuk", 0),
    ("şu an neşeliyim", 1),
    ("kendimi kötü hissediyorum", 0),
    ("çok neşeliyim", 1),
    ("biraz moralim düşük", 0),
    ("mutluluk doluyum", 1),
    ("mutsuz ve bitkinim", 0),
    ("bugün iyiyim", 1),
    ("kötü bir ruh halindeyim", 0),
    ("mutlu hissediyorum", 1),
    ("keyifsizim", 0),
    ("çok mutluyum ve huzurluyum", 1),
    ("moralim kötü", 0),
    ("enerjim yüksek", 1),
    ("biraz üzgünüm", 0),
    ("çok keyifliyim", 1),
    ("kötü hissediyorum", 0),
    ("neşeliyim", 1),
    ("moralsizim", 0),
    ("mutluyum ama yorgunum", 1),
    ("üzgün ve mutsuzum", 0),
    ("gülümsemek istiyorum", 1),
    ("kendimi kötü hissediyorum", 0),
    ("çok huzurluyum", 1),
    ("mutsuz bir gün geçiriyorum", 0),
    ("harika bir gün", 1),
    ("moralim düşük", 0),
    ("çok mutluyum ve pozitifim", 1),
    ("kendimi çok kötü hissediyorum", 0),
    ("neşem yerinde", 1),
    ("üzgünüm", 0),
    ("mutlu ve keyifliyim", 1),
    ("moralsiz ve mutsuzum", 0),
    ("bugün çok iyi hissediyorum", 1),
    ("çok kötü hissediyorum", 0),
    ("enerjim yüksek ve mutluyum", 1),
    ("moralim bozuk ve üzgünüm", 0),
    ("mutluluk içindeyim", 1),
    ("mutsuzum ve yorgunum", 0),
    ("çok keyifliyim ve pozitifim", 1),
    ("kendimi kötü ve bitkin hissediyorum", 0),
    ("gülümsemek istiyorum ve mutluyum", 1),
    ("üzgün ve moralsizim", 0),
    ("harika hissediyorum ve keyifliyim", 1),
    ("kötü bir ruh halindeyim", 0),
    ("neşem yerinde ve enerjim yüksek", 1),
    ("moralsiz ve mutsuz hissediyorum", 0),
    ("mutluyum ve huzurluyum", 1),
    ("mutsuz ve yorgunum", 0),
    ("çok keyifliyim ve gülümsemek istiyorum", 1),
    ("üzgün ve bitkinim", 0),
    ("bugün çok mutluyum", 1),
    ("kendimi kötü hissediyorum", 0),
    ("neşeliyim ve enerjim yüksek", 1),
    ("moralsiz ve mutsuzum", 0),
    ("mutlu hissediyorum", 1),
    ("üzgün ve keyifsizim", 0),
    ("harika hissediyorum", 1),
    ("moralim bozuk", 0),
    ("çok mutluyum ve pozitifim", 1),
    ("mutsuz ve yorgunum", 0),
    ("neşeliyim", 1),
    ("kötü hissediyorum", 0),
    ("mutluyum ve huzurluyum", 1),
    ("üzgünüm", 0),
    ("keyfim yerinde", 1),
    ("moralsizim", 0),
    ("çok keyifliyim", 1),
    ("mutsuzum", 0),
    ("gülümsemek istiyorum", 1),
    ("kendimi kötü hissediyorum", 0),
    ("mutluluk doluyum", 1),
    ("moralsiz ve üzgünüm", 0),
    ("enerjim yüksek", 1),
    ("kötü bir gün geçiriyorum", 0),
    ("çok mutluyum ve neşeliyim", 1),
    ("üzgün ve moralsizim", 0),
    ("harika bir ruh halindeyim", 1),
    ("mutsuz ve bitkinim", 0),
    ("mutluyum", 1),
    ("kendimi kötü hissediyorum", 0),
    ("neşem yerinde", 1),
    ("moralsiz ve mutsuzum", 0),
    ("çok keyifliyim", 1),
    ("üzgün ve yorgunum", 0),
    ("gülümsemek istiyorum", 1),
    ("kötü hissediyorum", 0),
    ("mutluyum ve huzurluyum", 1),
    ("moralim bozuk", 0),
    ("enerjim yüksek ve mutluyum", 1),
    ("mutsuz ve moralsizim", 0),
    ("harika hissediyorum", 1),
    ("üzgünüm", 0),
    ("çok mutluyum ve pozitifim", 1),
    ("moralsiz ve mutsuzum", 0),
    ("neşeliyim", 1),
    ("kötü bir ruh halindeyim", 0),
    ("mutluluk içindeyim", 1),
    ("mutsuz ve yorgunum", 0),
    ("bugün çok keyifliyim", 1),
    ("kendimi kötü hissediyorum", 0),
        # Pozitif cümleler (1)
    ("çok mutluyum", 1),
    ("harika bir gün", 1),
    ("güneşli ve güzel bir sabah", 1),
    ("başarıyla tamamladım", 1),
    ("sevinçliyim", 1),
    ("harika hissediyorum", 1),
    ("moralim çok iyi", 1),
    ("güzel bir sürpriz aldım", 1),
    ("çok şanslıyım", 1),
    ("heyecanlıyım", 1),
    ("harika bir haber aldım", 1),
    ("kendimi harika hissediyorum", 1),
    ("çok neşeliyim", 1),
    ("pozitif enerji doluyum", 1),
    ("keyfim yerinde", 1),
    ("çok heyecanlıyım", 1),
    ("mutlu bir gün geçiriyorum", 1),
    ("başarılı oldum", 1),
    ("güzel bir tatil planladım", 1),
    ("çok huzurluyum", 1),
    ("çok gururluyum", 1),
    ("heyecan verici bir fırsat", 1),
    ("gülümsemek istiyorum", 1),
    ("iyi hissediyorum", 1),
    ("güzel bir gün", 1),
    ("enerjim yüksek", 1),
    ("harika bir başlangıç", 1),
    ("çok umutluyum", 1),
    ("başarı beni mutlu etti", 1),
    ("çok keyifliyim", 1),
    ("güzel bir yemek yedim", 1),
    ("pozitif bir gün", 1),
    ("kendimi iyi hissediyorum", 1),
    ("çok tatmin oldum", 1),
    ("harika bir etkinlik", 1),
    ("çok eğleniyorum", 1),
    ("güzel bir sürpriz", 1),
    ("çok motiveyim", 1),
    ("mutluluk doluyum", 1),
    ("harika bir haber", 1),
    ("keyfim çok yerinde", 1),
    ("çok başarılı hissediyorum", 1),
    ("güzel bir anı", 1),
    ("pozitif bir enerji", 1),
    ("çok sevindim", 1),
    ("harika bir başlangıç yaptım", 1),
    ("çok mutluyum bugün", 1),
    ("çok neşeliyim", 1),
    ("iyi hisler içerisindeyim", 1),
    ("çok huzurluyum", 1),
    ("başarıdan dolayı mutluyum", 1),
    ("gülmek istiyorum", 1),
    ("çok keyifli bir gün", 1),
    ("her şey yolunda", 1),
    ("çok sevindim bugün", 1),
    ("harika bir deneyim", 1),
    ("mutluluk verici bir an", 1),
    ("çok umutluyum bugün", 1),
    ("pozitif düşüncelerle doluyum", 1),
    ("başarıya ulaştım", 1),
    ("çok memnunum", 1),
    ("harika bir tatil geçirdim", 1),
    ("çok mutlu oldum", 1),
    ("güzel bir sürprizle karşılaştım", 1),
    ("çok heyecanlı ve mutluyum", 1),
    ("pozitif bir başlangıç", 1),
    ("çok keyifliyim bugün", 1),
    ("harika bir haberle sevindim", 1),
    ("çok şanslı hissettim", 1),
    ("güzel bir gün geçirdim", 1),
    ("çok motiveyim bugün", 1),
    ("başarı beni gururlandırdı", 1),
    ("çok neşeliyim bugün", 1),
    ("çok keyifli vakit geçirdim", 1),
    ("çok huzurluyum bugün", 1),
    ("pozitif bir enerji hissediyorum", 1),
    ("çok mutluyum bu an için", 1),
    ("güzel bir gün yaşadım", 1),
    ("çok sevindim bu yüzden", 1),
    ("harika bir his", 1),
    ("çok keyifli bir deneyim", 1),
    ("çok heyecanlı ve mutluyum", 1),
    ("pozitif bir ruh halindeyim", 1),
    ("çok tatmin oldum bugün", 1),
    ("başarıdan dolayı mutluyum", 1),
    ("çok gururluyum bugün", 1),
    ("güzel bir haber aldım bugün", 1),
    ("çok neşeliyim bu an", 1),
    ("çok mutluyum ve huzurluyum", 1),
    ("pozitif bir gün geçirdim", 1),
    ("çok keyifli bir gün", 1),
    ("harika bir başlangıç yaptım bugün", 1),
    ("çok motive oldum", 1),
    ("çok mutlu hissettim", 1),
    ("güzel bir gün yaşamak harika", 1),
    ("çok sevindim bu an için", 1),
    ("çok keyif aldım", 1),
    ("pozitif duygular içerisindeyim", 1),
    ("çok heyecanlı ve keyifliyim", 1),
    ("çok mutluyum ve başarılıyım", 1),
    ("harika bir gün geçirdim", 1),
    ("çok sevindim bugün", 1),
    ("pozitif bir ruh halindeyim bugün", 1),
    ("çok keyifli ve mutluyum", 1),
    ("çok huzurluyum ve mutlu", 1),
    ("çok gururluyum bu an için", 1),
    ("çok tatmin oldum bu yüzden", 1),
    ("güzel bir an yaşadım", 1),
    ("çok mutluyum ve heyecanlıyım", 1),
    ("pozitif bir başlangıç yaptım", 1),
    ("çok neşeliyim ve keyifliyim", 1),
    ("çok şanslı ve mutluyum", 1),
    ("çok keyif aldım bugün", 1),
    ("çok motivasyonluyum", 1),
    ("çok mutluyum ve pozitifim", 1),
    ("harika bir gün yaşadım", 1),
    ("çok heyecanlı ve neşeliyim", 1),
    ("çok keyifliyim ve huzurluyum", 1),
    ("çok mutlu ve motiveyim", 1),
    ("pozitif bir deneyim yaşadım", 1),
    ("çok gururluyum ve mutluyum", 1),
    ("çok tatmin oldum bugün", 1),
    ("çok heyecanlı ve başarılıyım", 1),
    ("çok neşeliyim ve pozitifim", 1),
    ("çok keyifli bir an yaşadım", 1),
    ("çok mutluyum ve heyecanlıyım", 1),
    ("harika bir his yaşadım", 1),
    ("çok motivasyonluyum ve mutluyum", 1),
    ("çok keyif aldım bu an için", 1),
    ("çok mutlu ve pozitif bir ruh halindeyim", 1),
    ("pozitif bir gün yaşadım", 1),
    ("çok huzurluyum ve keyifliyim", 1),
    ("çok heyecanlı ve tatmin oldum", 1),
    ("çok gururluyum ve keyifliyim", 1),
    ("çok mutluyum ve şanslıyım", 1),
    ("harika bir deneyim yaşadım", 1),
    ("çok keyifli ve heyecanlıyım", 1),
    ("pozitif bir enerji doluyum", 1),
    ("çok mutlu ve neşeliyim", 1),
    ("çok heyecanlı ve motiveyim", 1),
    ("çok keyif aldım bugün", 1),
    ("çok huzurluyum ve mutlu", 1),
    ("çok mutluyum ve başarılıyım", 1),
    ("harika bir başlangıç yaşadım", 1),
    ("pozitif bir ruh halindeyim", 1),
    ("çok motivasyonluyum ve keyifliyim", 1),
    ("çok neşeliyim ve mutluyum", 1),
    ("çok heyecanlı ve şanslıyım", 1),
    ("çok keyifli ve huzurluyum", 1),
    ("çok mutluyum ve pozitif enerji doluyum", 1),
    ("harika bir gün yaşamak çok güzel", 1),
    ("çok motivasyonluyum bugün", 1),
    ("çok heyecanlı ve tatmin oldum", 1),
    ("çok keyif aldım ve mutluyum", 1),
    ("pozitif bir gün geçirdim bugün", 1),
    ("çok gururluyum ve motiveyim", 1),
    ("çok mutluyum ve keyifliyim", 1),
    ("harika bir haberle sevindim", 1),
    ("çok heyecanlı ve neşeliyim", 1),
    ("çok huzurluyum ve başarılıyım", 1),
    ("pozitif bir enerji hissettim", 1),
    ("çok mutlu ve tatmin oldum", 1),
    ("çok keyifli ve heyecanlıyım", 1),
    ("çok mutluyum ve gururluyum", 1),
    ("harika bir gün geçirdim bugün", 1),
    ("pozitif bir ruh halindeyim bugün", 1),
    ("çok heyecanlı ve pozitifim", 1),
    ("çok motivasyonluyum ve mutluyum", 1),
    ("çok keyif aldım ve huzurluyum", 1),
    ("çok mutluyum ve şanslıyım bugün", 1),
    ("harika bir deneyim yaşadım bugün", 1),
    ("çok heyecanlı ve keyifliyim", 1),
    ("pozitif bir enerji doluyum bugün", 1),
    ("çok mutlu ve motiveyim", 1),
    ("çok keyifli ve neşeliyim", 1),
    ("çok mutluyum ve tatmin oldum", 1),
    ("harika bir gün yaşadım bugün", 1),
    ("pozitif bir ruh halindeyim şimdi", 1),
    ("çok heyecanlı ve gururluyum", 1),
    ("çok keyif aldım ve pozitifim", 1),
    ("çok mutluyum ve heyecanlıyım bugün", 1),
    ("harika bir haber aldım bugün", 1),
    ("pozitif bir enerji hissettim bugün", 1),
    ("çok motivasyonluyum ve heyecanlıyım", 1),
    ("çok neşeliyim ve keyifliyim", 1),
    ("çok mutluyum ve gururluyum bugün", 1),
    ("harika bir gün yaşamak çok keyifli", 1),
    ("pozitif bir ruh halindeyim şimdi", 1),
    ("çok heyecanlı ve motiveyim bugün", 1),
    ("çok keyif aldım ve mutluyum bugün", 1),
    ("çok mutluyum ve pozitif enerji doluyum bugün", 1),
    # Negatif cümleler (0)
    ("çok üzgünüm", 0),
    ("berbat bir gün", 0),
    ("hiç mutlu değilim", 0),
    ("moralsizim", 0),
    ("kötü bir haber aldım", 0),
    ("çok sıkıldım", 0),
    ("kendimi kötü hissediyorum", 0),
    ("mutsuzum", 0),
    ("çok yorgunum", 0),
    ("olumsuz bir gün", 0),
    ("üzücü bir haber", 0),
    ("kötü bir başlangıç", 0),
    ("huzursuzum", 0),
    ("hayal kırıklığına uğradım", 0),
    ("çok stresliyim", 0),
    ("endişeliyim", 0),
    ("moralsiz bir gün", 0),
    ("hayal kırıklığı", 0),
    ("çok kötü hissediyorum", 0),
    ("keyfim yok", 0),
    ("çok kırgınım", 0),
    ("rahatsız hissediyorum", 0),
    ("çıkmazdayım", 0),
    ("çok karamsarım", 0),
    ("hayal kırıklığı içindeyim", 0),
    ("çok sinirliyim", 0),
    ("kötü bir olay", 0),
    ("üzücü bir durum", 0),
    ("hiç keyfim yok", 0),
    ("çok mutsuzum", 0),
    ("umutsuz hissediyorum", 0),
    ("çok hayal kırıklığına uğradım", 0),
    ("moralsiz ve mutsuzum", 0),
    ("çok endişeliyim", 0),
    ("kötü bir gün geçirdim", 0),
    ("çok yorgun ve üzgünüm", 0),
    ("çok sinirliyim bugün", 0),
    ("üzücü bir haber aldım", 0),
    ("mutsuzum ve keyifsizim", 0),
    ("moralsiz hissediyorum", 0),
    ("çok stresliyim bugün", 0),
    ("kötü bir başlangıç yaptım", 0),
    ("çok üzgün ve kırgınım", 0),
    ("hiç mutlu değilim bugün", 0),
    ("çok karamsarım bugün", 0),
    ("çok rahatsız hissediyorum", 0),
    ("üzücü bir deneyim yaşadım", 0),
    ("çok mutsuzum ve yorgunum", 0),
    ("moralsiz ve endişeliyim", 0),
    ("çok hayal kırıklığı içindeyim", 0),
    ("çok sinirliyim ve üzgünüm", 0),
    ("çok mutsuz ve moralsizim", 0),
    ("kötü bir haber aldım bugün", 0),
    ("çok yorgun ve karamsarım", 0),
    ("üzücü bir olay yaşadım", 0),
    ("çok mutsuz ve stresliyim", 0),
    ("hiç keyfim yok bugün", 0),
    ("çok endişeli ve moralsizim", 0),
    ("çok sinirliyim ve yorgunum", 0),
    ("moralsiz ve mutsuz bir gün", 0),
    ("çok kötü hissediyorum bugün", 0),
    ("çok üzgün ve karamsarım", 0),
    ("kötü bir deneyim yaşadım", 0),
    ("çok hayal kırıklığına uğradım bugün", 0),
    ("moralsiz ve stresliyim", 0),
    ("çok mutsuz ve rahatsız hissediyorum", 0),
    ("hiç mutlu değilim bu an", 0),
    ("çok sinirliyim ve moralsizim", 0),
    ("çok üzgün ve endişeliyim", 0),
    ("kötü bir gün geçirdim bugün", 0),
    ("çok yorgun ve mutsuzum", 0),
    ("moralsiz ve rahatsız hissediyorum", 0),
    ("çok hayal kırıklığı yaşadım", 0),
    ("çok sinirliyim ve stresliyim", 0),
    ("çok mutsuz ve karamsarım", 0),
    ("üzücü bir haber aldım bugün", 0),
    ("hiç keyfim yok bu an", 0),
    ("çok moralsiz ve endişeliyim", 0),
    ("çok yorgun ve sinirliyim", 0),
    ("kötü bir başlangıç yaptım bugün", 0),
    ("çok mutsuz ve rahatsızım", 0),
    ("moralsiz ve üzgünüm", 0),
    ("çok stresliyim ve mutsuzum", 0),
    ("çok sinirliyim ve karamsarım", 0),
    ("üzücü bir deneyim yaşadım bugün", 0),
    ("çok mutsuz ve endişeliyim", 0),
    ("hiç mutlu değilim ve moralsizim", 0),
    ("çok yorgun ve rahatsızım", 0),
    ("moralsiz ve hayal kırıklığı içindeyim", 0),
    ("çok üzgün ve stresliyim", 0),
    ("kötü bir haberle karşılaştım", 0),
    ("çok mutsuz ve sinirliyim", 0),
    ("moralsiz ve yorgunum", 0),
    ("çok hayal kırıklığına uğradım bu an", 0),
    ("çok mutsuz ve rahatsız hissediyorum", 0),
    ("hiç keyfim yok ve karamsarım", 0),
    ("çok sinirliyim ve üzgünüm", 0),
    ("kötü bir gün geçirdim bu an", 0),
    ("moralsiz ve endişeliyim bugün", 0),
    ("çok mutsuz ve stresliyim", 0),
    ("üzücü bir haber aldım bu an", 0),
    ("çok yorgun ve moralsizim", 0),
    ("moralsiz ve mutsuz bir gün", 0),
    ("çok sinirliyim ve yorgunum", 0),
    ("çok üzgün ve karamsarım bugün", 0),
    ("kötü bir deneyim yaşadım bugün", 0),
    ("çok mutsuz ve rahatsızım bu an", 0),
    ("moralsiz ve stresliyim bugün", 0),
    ("çok hayal kırıklığı yaşadım bugün", 0),
        ("hiç mutlu değilim bu an", 0),
    ("çok mutsuz ve moralsizim", 0),
    ("çok yorgun ve stresliyim", 0),
    ("moralsiz ve karamsarım", 0),
    ("çok sinirliyim ve rahatsızım", 0),
    ("üzücü bir olay yaşadım bugün", 0),
    ("çok mutsuz ve endişeliyim bugün", 0),
    ("kötü bir haber aldım bu an", 0),
    ("moralsiz ve mutsuz bir gün", 0),
    ("çok hayal kırıklığına uğradım bu an", 0),
    ("çok yorgun ve moralsizim bugün", 0),
    ("hiç keyfim yok ve stresliyim", 0),
    ("çok sinirliyim ve mutsuzum", 0),
    ("üzücü bir haberle karşılaştım bugün", 0),
    ("kötü bir gün geçirdim bu an", 0),
    ("moralsiz ve yorgunum bugün", 0),
    ("çok mutsuz ve rahatsız hissediyorum", 0),
    ("çok sinirliyim ve endişeliyim", 0),
    ("kötü bir başlangıç yaptım bu gün", 0),
    ("moralsiz ve hayal kırıklığı içindeyim", 0),
    ("çok üzgün ve karamsarım", 0),
    ("çok mutsuz ve stresliyim bugün", 0),
    ("hiç keyfim yok ve mutsuzum", 0),
    ("çok sinirliyim ve moralsizim bugün", 0),
    ("moralsiz ve yorgun hissediyorum", 0),
    ("çok hayal kırıklığına uğradım bugün", 0),
    ("çok mutsuz ve rahatsızım bugün", 0),
    ("üzücü bir deneyim yaşadım bu an", 0),
    ("çok sinirliyim ve karamsarım bugün", 0),
    ("moralsiz ve stresliyim bugün", 0),
    ("çok mutsuz ve endişeliyim", 0),
    ("hiç mutlu değilim ve keyfim yok", 0),
    ("çok yorgun ve rahatsız hissediyorum", 0),
    ("moralsiz ve hayal kırıklığı içindeyim bugün", 0),
    ("çok üzgün ve stresliyim", 0),
    ("kötü bir haberle karşılaştım bu an", 0),
    ("çok mutsuz ve sinirliyim bugün", 0),
    ("moralsiz ve yorgunum bugün", 0),
    ("çok hayal kırıklığı yaşadım bu an", 0),
    ("hiç keyfim yok ve karamsarım bugün", 0),
    ("çok mutsuz ve rahatsız hissediyorum", 0),
    ("üzücü bir haber aldım bugün", 0),
    ("çok sinirliyim ve moralsizim bugün", 0),
    ("moralsiz ve mutsuz bir gün bugün", 0),
    ("çok yorgun ve endişeliyim", 0),
    ("hiç mutlu değilim ve rahatsız hissediyorum", 0),
    ("çok sinirliyim ve stresliyim", 0),
    ("kötü bir deneyim yaşadım bugün", 0),
    ("moralsiz ve hayal kırıklığı içindeyim bu gün", 0),
    ("çok mutsuz ve karamsarım", 0),
    ("hiç keyfim yok ve mutsuzum bugün", 0),
    ("çok sinirliyim ve rahatsızım bugün", 0),
    ("üzücü bir olay yaşadım bu gün", 0),
    ("çok mutsuz ve moralsizim bugün", 0),
    ("moralsiz ve yorgunum bu gün", 0),
    ("çok hayal kırıklığına uğradım bu gün", 0),
    ("çok mutsuz ve endişeliyim bugün", 0),
    ("hiç mutlu değilim ve karamsarım", 0),
    ("çok yorgun ve stresliyim bugün", 0),
    ("moralsiz ve mutsuzum bugün", 0),
    ("çok sinirliyim ve rahatsız hissediyorum", 0),
    ("üzücü bir haber aldım bu gün", 0),
    ("kötü bir başlangıç yaptım bugün", 0),
    ("çok mutsuz ve karamsarım bugün", 0),
    ("moralsiz ve stresliyim bu gün", 0),
    ("çok hayal kırıklığı yaşadım bugün", 0),
    ("hiç keyfim yok ve moralsizim", 0),
    ("çok sinirliyim ve endişeliyim bugün", 0),
    ("moralsiz ve yorgun hissediyorum bugün", 0),
    ("çok mutsuz ve rahatsızım bu gün", 0),
    ("üzücü bir deneyim yaşadım bugün", 0),
    ("çok sinirliyim ve karamsarım bu gün", 0),
    ("moralsiz ve stresliyim bugün", 0),
    ("çok mutsuz ve endişeliyim bugün", 0),
    ("hiç mutlu değilim ve mutsuzum bugün", 0),
    ("çok yorgun ve rahatsız hissediyorum bugün", 0),
    ("moralsiz ve hayal kırıklığı içindeyim bugün", 0),
    ("çok üzgün ve stresliyim bugün", 0),
    ("kötü bir haberle karşılaştım bugün", 0),
    ("çok mutsuz ve sinirliyim bugün", 0),
    ("moralsiz ve yorgunum bugün", 0),
    ("çok hayal kırıklığı yaşadım bugün", 0),
    ("hiç keyfim yok ve karamsarım bugün", 0),
        ("çok mutluyum ve heyecanlıyım", 1),
    ("güzel bir gün geçiriyorum", 1),
    ("çok sevindim bugün", 1),
    ("harika bir haber aldım", 1),
    ("keyfim yerinde ve neşeliyim", 1),
    ("çok pozitif hissediyorum", 1),
    ("çok enerjik ve mutluyum", 1),
    ("çok motiveyim bugün", 1),
    ("güzel bir sürprizle karşılaştım", 1),
    ("çok tatmin oldum", 1),
    ("çok heyecanlıyım ve mutlu", 1),
    ("harika bir anı yaşadım", 1),
    ("pozitif bir enerji hissediyorum", 1),
    ("çok neşeliyim ve keyifliyim", 1),
    ("çok gururluyum ve mutluyum", 1),
    ("başarıdan dolayı çok mutluyum", 1),
    ("çok heyecanlı ve tatmin oldum", 1),
    ("harika bir başlangıç yaptım bugün", 1),
    ("çok keyifli bir gün geçirdim", 1),
    ("çok huzurluyum ve mutlu", 1),
    ("pozitif bir ruh halindeyim bugün", 1),
    ("çok mutlu ve motiveyim", 1),
    ("çok keyif aldım bu an için", 1),
    ("harika bir gün yaşamak çok güzel", 1),
    ("çok heyecanlı ve pozitifim", 1),
    ("çok neşeliyim ve huzurluyum", 1),
    ("çok gururluyum ve keyifliyim", 1),
    ("çok mutluyum ve enerjikim", 1),
    ("pozitif bir gün geçirdim bugün", 1),
    ("çok tatmin oldum ve mutlu", 1),
    ("harika bir haberle sevindim", 1),
    ("çok heyecanlı ve gururluyum", 1),
    ("çok keyifli ve neşeliyim", 1),
    ("çok mutlu ve pozitif enerji doluyum", 1),
    ("harika bir deneyim yaşadım", 1),
    ("çok motive ve heyecanlıyım", 1),
    ("çok huzurluyum ve keyifliyim", 1),
    ("pozitif bir ruh halindeyim", 1),
    ("çok mutluyum ve gururluyum bugün", 1),
    ("çok keyif aldım ve heyecanlıyım", 1),
    ("harika bir gün geçirdim bugün", 1),
    ("çok heyecanlı ve tatmin oldum bugün", 1),
    ("çok mutlu ve keyifliyim bugün", 1),
    ("pozitif bir enerji doluyum bugün", 1),
    ("çok neşeliyim ve motiveyim", 1),
    ("çok gururluyum ve huzurluyum", 1),
    ("çok mutluyum ve enerjim yüksek", 1),
    ("harika bir başlangıç yaşadım", 1),
    ("çok heyecanlı ve pozitifim bugün", 1),
    ("çok keyifli ve tatmin oldum", 1),
    ("pozitif bir gün geçirdim", 1),
    ("çok mutlu ve heyecanlıyım", 1),
    ("harika bir an yaşamak çok güzel", 1),
    ("çok neşeliyim ve gururluyum", 1),
    ("çok keyif aldım ve mutlu", 1),
    ("pozitif bir enerji hissediyorum bugün", 1),
    ("çok huzurluyum ve motiveyim", 1),
    ("çok mutluyum ve tatmin oldum", 1),
    ("harika bir haberle sevindim bugün", 1),
    ("çok heyecanlı ve enerjikim", 1),
    ("çok gururluyum ve keyifliyim bugün", 1),
    ("çok neşeliyim ve pozitifim", 1),
    ("pozitif bir ruh halindeyim bu an", 1),
    ("çok mutlu ve keyifli bir gün", 1),
    ("harika bir gün yaşamak çok keyifli", 1),
    ("çok motive ve neşeliyim", 1),
    ("çok huzurluyum ve enerjim yüksek", 1),
    ("pozitif bir deneyim yaşadım", 1),
    ("çok heyecanlı ve gururluyum bugün", 1),
    ("çok keyifli ve mutlu", 1),
    ("çok mutluyum ve pozitif enerji doluyum bugün", 1),
    ("harika bir başlangıç yaptım", 1),
    ("çok neşeliyim ve heyecanlıyım", 1),
    ("pozitif bir gün geçiriyorum", 1),
    ("çok gururluyum ve motiveyim", 1),
    ("çok mutlu ve tatmin oldum bugün", 1),
    ("harika bir deneyim yaşadım bugün", 1),
    ("çok heyecanlı ve keyifliyim", 1),
    ("çok huzurluyum ve neşeliyim", 1),
    ("pozitif bir enerji hissediyorum bu an", 1),
    ("çok mutluyum ve gururluyum bu an", 1),
    ("çok keyif aldım ve heyecanlıyım bugün", 1),
    ("harika bir gün geçirdim bu an", 1),
    ("çok neşeliyim ve pozitifim bugün", 1),
    ("çok motivasyonluyum ve mutlu", 1),
    ("pozitif bir ruh halindeyim şimdi", 1),
    ("çok mutluyum ve enerjikim bugün", 1),
    ("çok keyifli ve heyecanlıyım bugün", 1),
    ("harika bir haber aldım bu an", 1),
    ("çok heyecanlı ve gururluyum bu an", 1),
    ("çok huzurluyum ve pozitifim", 1),
    ("pozitif bir gün yaşamak çok güzel", 1),
    ("çok mutluyum ve keyifliyim bu an", 1),
    ("harika bir deneyim yaşamak çok güzel", 1),
    ("çok heyecanlı ve tatmin oldum bu an", 1),
    ("çok neşeliyim ve gururluyum bu an", 1),
    ("pozitif bir enerji doluyum bu an", 1),
    ("çok mutluyum ve motiveyim bu an", 1),
    ("çok keyifli ve enerjikim", 1),
    ("harika bir gün yaşadım bu an", 1),
    ("çok heyecanlı ve pozitifim bu an", 1),
    ("pozitif bir ruh halindeyim bu gün", 1),
    ("çok mutlu ve gururluyum bu gün", 1),
    ("çok neşeliyim ve heyecanlıyım bu gün", 1),
    ("harika bir başlangıç yaptım bu gün", 1),
    ("çok mutluyum ve keyif aldım bu gün", 1),
    ("çok heyecanlı ve tatmin oldum bu gün", 1),
    ("pozitif bir gün geçiriyorum bu gün", 1),
    ("çok gururluyum ve motivasyonluyum", 1),
    ("çok mutluyum ve pozitifim bu gün", 1),
    ("harika bir deneyim yaşadım bu gün", 1),
    ("çok heyecanlı ve keyifliyim bu gün", 1),
    ("çok huzurluyum ve neşeliyim bu gün", 1),
    ("pozitif bir enerji hissediyorum bu gün", 1),
    ("çok mutluyum ve gururluyum bu gün", 1),
    ("çok keyif aldım ve heyecanlıyım bu gün", 1),
    ("harika bir gün geçirdim bu gün", 1),
    ("çok neşeliyim ve pozitifim bu gün", 1),
    ("çok motivasyonluyum ve mutluyum bu gün", 1),
    ("pozitif bir ruh halindeyim bu gün", 1),
    ("çok mutluyum ve enerjikim bu gün", 1),
    ("çok keyifli ve heyecanlıyım bu gün", 1),
    ("harika bir haber aldım bu gün", 1),
    ("çok heyecanlı ve gururluyum bu gün", 1),
    ("çok huzurluyum ve pozitifim bu gün", 1),
    ("pozitif bir gün yaşamak çok keyifli", 1),
    ("çok mutluyum ve keyifliyim bu gün", 1),
    ("harika bir deneyim yaşamak çok keyifli", 1),
    ("çok heyecanlı ve tatmin oldum bu gün", 1),
    ("çok neşeliyim ve gururluyum bu gün", 1),
    ("pozitif bir enerji doluyum bu gün", 1),
    ("çok mutluyum ve motiveyim bu gün", 1),
    ("çok keyifli ve enerjikim bu gün", 1),
    ("harika bir gün yaşadım bu gün", 1),
    ("çok heyecanlı ve pozitifim bu gün", 1),
    ("pozitif bir ruh halindeyim bu gün", 1),
    ("çok mutlu ve gururluyum bu gün", 1),
    ("çok neşeliyim ve heyecanlıyım bu gün", 1),
    ("harika bir başlangıç yaptım bu gün", 1),
    ("çok mutluyum ve keyif aldım bu gün", 1),
    ("çok heyecanlı ve tatmin oldum bu gün", 1),
    ("pozitif bir gün geçiriyorum bu gün", 1),
    ("çok gururluyum ve motivasyonluyum", 1),
    ("çok mutluyum ve pozitifim bu gün", 1),
    ("çok üzgünüm ve moralsizim", 0),
    ("berbat bir gün geçirdim", 0),
    ("hiç mutlu değilim bugün", 0),
    ("moralsiz ve yorgunum", 0),
    ("kötü bir haber aldım bugün", 0),
    ("çok sıkıldım ve mutsuzum", 0),
    ("kendimi kötü hissediyorum bugün", 0),
    ("mutsuzum ve keyifsizim", 0),
    ("çok yorgunum ve moralsizim", 0),
    ("olumsuz bir gün geçiriyorum", 0),
    ("üzücü bir haber aldım bugün", 0),
    ("kötü bir başlangıç yaptım bugün", 0),
    ("huzursuzum ve karamsarım", 0),
    ("hayal kırıklığına uğradım bugün", 0),
    ("çok stresliyim ve üzgünüm", 0),
    ("endişeliyim ve moralsizim", 0),
    ("moralsiz bir gün geçiriyorum", 0),
    ("hayal kırıklığı içindeyim bugün", 0),
    ("çok kötü hissediyorum bugün", 0),
    ("keyfim yok ve mutsuzum", 0),
    ("çok kırgınım ve huzursuzum", 0),
    ("rahatsız hissediyorum bugün", 0),
    ("çıkmazdayım ve endişeliyim", 0),
    ("çok karamsarım bugün", 0),
    ("hayal kırıklığı içindeyim bu gün", 0),
    ("çok sinirliyim ve moralsizim", 0),
    ("kötü bir olay yaşadım bugün", 0),
    ("üzücü bir durum yaşadım", 0),
    ("hiç keyfim yok ve karamsarım", 0),
    ("çok mutsuzum ve üzgünüm", 0),
    ("umutsuz hissediyorum bugün", 0),
    ("çok hayal kırıklığına uğradım bu gün", 0),
    ("moralsiz ve mutsuz hissediyorum", 0),
    ("çok endişeliyim ve karamsarım", 0),
    ("kötü bir gün geçirdim bugün", 0),
    ("çok yorgun ve üzgünüm", 0),
    ("çok sinirliyim bugün ve moralsizim", 0),
    ("üzücü bir haber aldım bu gün", 0),
    ("mutsuzum ve keyifsizim bugün", 0),
    ("moralsiz hissediyorum bugün", 0),
    ("çok stresliyim bugün ve mutsuzum", 0),
    ("kötü bir başlangıç yaptım bu gün", 0),
    ("çok üzgün ve kırgınım", 0),
    ("hiç mutlu değilim bugün ve karamsarım", 0),
    ("çok karamsarım ve moralsizim", 0),
    ("çok rahatsız hissediyorum bugün", 0),
    ("üzücü bir deneyim yaşadım bugün", 0),
    ("çok mutsuz ve yorgunum bugün", 0),
    ("moralsiz ve endişeliyim bugün", 0),
    ("çok hayal kırıklığı içindeyim bugün", 0),
    ("çok sinirliyim ve üzgünüm bugün", 0),
    ("çok mutsuz ve moralsizim bugün", 0),
    ("kötü bir haber aldım bu gün", 0),
    ("çok yorgun ve karamsarım bugün", 0),
    ("üzücü bir olay yaşadım bu gün", 0),
    ("çok mutsuz ve stresliyim bugün", 0),
    ("hiç keyfim yok ve moralsizim bugün", 0),
    ("çok endişeli ve karamsarım bugün", 0),
    ("çok sinirliyim ve yorgunum bugün", 0),
    ("moralsiz ve mutsuz bir gün bugün", 0),
    ("çok kötü hissediyorum bugün ve üzgünüm", 0),
    ("çok üzgün ve karamsarım bugün", 0),
    ("kötü bir deneyim yaşadım bu gün", 0),
    ("çok mutsuz ve rahatsızım bugün", 0),
    ("moralsiz ve stresliyim bugün", 0),
    ("çok hayal kırıklığı yaşadım bu gün", 0),
    ("hiç keyfim yok ve moralsizim bugün", 0),
    ("çok sinirliyim ve endişeliyim bugün", 0),
    ("moralsiz ve yorgun hissediyorum bugün", 0),
    ("çok mutsuz ve rahatsızım bugün", 0),
    ("üzücü bir deneyim yaşadım bu gün", 0),
    ("çok sinirliyim ve karamsarım bugün", 0),
    ("moralsiz ve stresliyim bugün", 0),
    ("çok mutsuz ve endişeliyim bugün", 0),
    ("hiç mutlu değilim ve mutsuzum bugün", 0),
    ("çok yorgun ve rahatsız hissediyorum bugün", 0),
    ("moralsiz ve hayal kırıklığı içindeyim bugün", 0),
    ("çok üzgün ve stresliyim bugün", 0),
    ("kötü bir haberle karşılaştım bugün", 0),
    ("çok mutsuz ve sinirliyim bugün", 0),
    ("moralsiz ve yorgunum bugün", 0),
    ("çok hayal kırıklığı yaşadım bugün", 0),
    ("hiç keyfim yok ve karamsarım bugün", 0),
    ("çok mutsuz ve rahatsız hissediyorum bugün", 0),
    ("üzücü bir haber aldım bugün", 0),
    ("çok sinirliyim ve moralsizim bugün", 0),
    ("moralsiz ve mutsuz bir gün bugün", 0),
    ("çok yorgun ve endişeliyim bugün", 0),
    
    ("hiç mutlu değilim ve rahatsız hissediyorum bugün", 0),


    ("çok sinirliyim ve stresliyim bugün", 0),
    ("kötü bir deneyim yaşadım bugün", 0),
    ("moralsiz ve hayal kırıklığı içindeyim bu gün", 0),
    ("çok mutsuz ve karamsarım bugün", 0),
    ("hiç keyfim yok ve mutsuzum bugün", 0),
    ("çok sinirliyim ve rahatsızım bugün", 0),
    ("üzücü bir olay yaşadım bu gün", 0),
    ("çok mutsuz ve moralsizim bugün", 0),
    ("moralsiz ve yorgunum bu gün", 0),
    ("çok hayal kırıklığına uğradım bu gün", 0),
    ("çok mutsuz ve endişeliyim bugün", 0),
    ("hiç mutlu değilim ve karamsarım", 0),
    ("çok yorgun ve stresliyim bugün", 0),
    ("moralsiz ve mutsuzum bugün", 0),
    ("çok sinirliyim ve rahatsız hissediyorum", 0),
    ("üzücü bir haber aldım bu gün", 0),
    ("kötü bir başlangıç yaptım bugün", 0),
    ("çok mutsuz ve karamsarım bugün", 0),
    ("moralsiz ve stresliyim bu gün", 0),
    ("çok hayal kırıklığı yaşadım bugün", 0),
    
    # Çelişkili durumlar - "ama" ile olumlu sonuçlanan cümleler
    ("biraz yorgunum ama keyfim yerinde", 1),
    ("yorgunum ama mutluyum", 1),
    ("biraz üzgünüm ama keyfim yerinde", 1),
    ("moralsizim ama toparlanıyorum", 1),
    ("yorgunum ama neşeliyim", 1),
    ("biraz mutsuzum ama keyfim yerinde", 1),
    ("yorgunum ama huzurluyum", 1),
    ("biraz kötüyüm ama keyfim yerinde", 1),
]
